version: "3.8"

services:
  frontend:
    build:
      context: ./biasappfe # <-- Ubah ke ./biasappfe
      dockerfile: Dockerfile
    container_name: biasapp-frontend
    restart: always
    env_file:
      - ./biasappfe/.env # <-- Arahkan ke file .env di dalam biasappfe
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
